exports.LANGS = {
  en: { full: 'english', name: '英语' },
  zh: { full: 'Simplified Chinese', name: '简体中文' },
  zt: { full: 'Traditional Chinese', name: '繁体中文' },
  es: { full: 'spanish', name: '西班牙语' },
  pt: { full: 'portuguese', name: '葡萄牙语' },
  fr: { full: 'french', name: '法语' },
  de: { full: 'german', name: '德语' },
  it: { full: 'italian', name: '意大利语' },
  ru: { full: 'russian', name: '俄语' },
  ja: { full: 'japanese', name: '日语' },
  ko: { full: 'korean', name: '韩语' },
  ar: { full: 'arabic', name: '阿拉伯语' },
  tr: { full: 'turkish', name: '土耳其语' },
  th: { full: 'thai', name: '泰语' },
  vi: { full: 'vietnamese', name: '越南语' },
  nl: { full: 'dutch', name: '荷兰语' },
  he: { full: 'hebrew', name: '希伯来语' },
  id: { full: 'indonesian', name: '印尼语' },
  pl: { full: 'polish', name: '波兰语' },
  hi: { full: 'hindi', name: '印地语' },
  uk: { full: 'urainian', name: '乌克兰语' },
};
